export const shopCategories = [
  { value: "electronics", label: "Electronics & Computers" },
  { value: "fashion", label: "Fashion & Apparel" },
  { value: "home_kitchen", label: "Home & Kitchen" },
  { value: "beauty_personal_care", label: "Beauty & Personal Care" },
  { value: "sports_fitness", label: "Sports & Fitness" },
  { value: "toys_kids_baby", label: "Toys, Kids & Baby" },
  { value: "books_media", label: "Books, Movies & Music" },
  { value: "health_wellness", label: "Health & Wellness" },
  { value: "automotive_industrial", label: "Automotive & Industrial" },
  { value: "grocery_gourmet", label: "Grocery & Gourmet Food" },
  { value: "pet_supplies", label: "Pet Supplies" },
  { value: "office_products", label: "Office Products & Stationery" },
  { value: "garden_outdoor", label: "Garden & Outdoor" },
  { value: "jewelry_watches", label: "Jewelry & Watches" },
  { value: "handmade_crafts", label: "Handmade & Crafts" },
  { value: "appliances", label: "Appliances & Home Improvement" },
  { value: "arts_entertainment", label: "Arts & Entertainment" },
  { value: "luggage_travel", label: "Luggage & Travel Accessories" },
  { value: "musical_instruments", label: "Musical Instruments" },
  { value: "gift_cards", label: "Gift Cards & Specialty Shops" },
];
